# Generated by Django 5.0.3 on 2024-07-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('add', models.CharField(max_length=300)),
                ('item', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=200)),
            ],
        ),
    ]
