# Generated by Django 5.0.3 on 2024-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
