# Generated by Django 5.0.3 on 2024-07-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vender',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vender',
            name='item',
        ),
        migrations.RemoveField(
            model_name='vender',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='vender',
            name='ref',
        ),
        migrations.AlterField(
            model_name='vender',
            name='add',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='aets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(blank=True, max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.vender')),
            ],
        ),
    ]
